/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proje;
import java.awt.Color;
import javax.swing.JPanel;
/**
 *
 * @author erene
 */
public class Mainform extends javax.swing.JFrame {

    private int xx;
    private int xy;

    /**
     * Creates new form Mainform
     */
    public Mainform() {
        initComponents();
        jTabbedPane1.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        toppanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sidepanel = new javax.swing.JPanel();
        logopanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        yonetimpanel = new javax.swing.JPanel();
        btn_yntm_uye_listele = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_yntm_uye_ekle = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_yntm_uye_guncelle = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_yntm_uye_sil = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_geri = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_yntm_musteri_listele = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        homepanel = new javax.swing.JPanel();
        btn_yntm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_misafir = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_uye = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toppanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout toppanelLayout = new javax.swing.GroupLayout(toppanel);
        toppanel.setLayout(toppanelLayout);
        toppanelLayout.setHorizontalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppanelLayout.createSequentialGroup()
                .addContainerGap(895, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(20, 20, 20))
        );
        toppanelLayout.setVerticalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        bg.add(toppanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -10, 940, 170));

        sidepanel.setBackground(new java.awt.Color(51, 51, 255));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logopanel.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGO");

        javax.swing.GroupLayout logopanelLayout = new javax.swing.GroupLayout(logopanel);
        logopanel.setLayout(logopanelLayout);
        logopanelLayout.setHorizontalGroup(
            logopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logopanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        logopanelLayout.setVerticalGroup(
            logopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logopanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        sidepanel.add(logopanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 270, 160));

        yonetimpanel.setBackground(new java.awt.Color(51, 51, 255));

        btn_yntm_uye_listele.setBackground(new java.awt.Color(51, 51, 255));
        btn_yntm_uye_listele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_listeleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_listeleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_listeleMousePressed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-male-30.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Üyeleri Listele");

        javax.swing.GroupLayout btn_yntm_uye_listeleLayout = new javax.swing.GroupLayout(btn_yntm_uye_listele);
        btn_yntm_uye_listele.setLayout(btn_yntm_uye_listeleLayout);
        btn_yntm_uye_listeleLayout.setHorizontalGroup(
            btn_yntm_uye_listeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_yntm_uye_listeleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_yntm_uye_listeleLayout.setVerticalGroup(
            btn_yntm_uye_listeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_yntm_uye_listeleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_yntm_uye_listeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        btn_yntm_uye_ekle.setBackground(new java.awt.Color(51, 51, 255));
        btn_yntm_uye_ekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_ekleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_ekleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_ekleMousePressed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-male-30.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Üye Ekle");

        javax.swing.GroupLayout btn_yntm_uye_ekleLayout = new javax.swing.GroupLayout(btn_yntm_uye_ekle);
        btn_yntm_uye_ekle.setLayout(btn_yntm_uye_ekleLayout);
        btn_yntm_uye_ekleLayout.setHorizontalGroup(
            btn_yntm_uye_ekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_yntm_uye_ekleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_yntm_uye_ekleLayout.setVerticalGroup(
            btn_yntm_uye_ekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_yntm_uye_ekleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_yntm_uye_ekleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        btn_yntm_uye_guncelle.setBackground(new java.awt.Color(51, 51, 255));
        btn_yntm_uye_guncelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_guncelleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_guncelleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_guncelleMousePressed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-male-30.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Üye Güncelle");

        javax.swing.GroupLayout btn_yntm_uye_guncelleLayout = new javax.swing.GroupLayout(btn_yntm_uye_guncelle);
        btn_yntm_uye_guncelle.setLayout(btn_yntm_uye_guncelleLayout);
        btn_yntm_uye_guncelleLayout.setHorizontalGroup(
            btn_yntm_uye_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_yntm_uye_guncelleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_yntm_uye_guncelleLayout.setVerticalGroup(
            btn_yntm_uye_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_yntm_uye_guncelleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_yntm_uye_guncelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        btn_yntm_uye_sil.setBackground(new java.awt.Color(51, 51, 255));
        btn_yntm_uye_sil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_silMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_silMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_yntm_uye_silMousePressed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-male-30.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Üye Sil");

        javax.swing.GroupLayout btn_yntm_uye_silLayout = new javax.swing.GroupLayout(btn_yntm_uye_sil);
        btn_yntm_uye_sil.setLayout(btn_yntm_uye_silLayout);
        btn_yntm_uye_silLayout.setHorizontalGroup(
            btn_yntm_uye_silLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_yntm_uye_silLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_yntm_uye_silLayout.setVerticalGroup(
            btn_yntm_uye_silLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_yntm_uye_silLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_yntm_uye_silLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        btn_geri.setBackground(new java.awt.Color(51, 51, 255));
        btn_geri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_geriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_geriMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_geriMousePressed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-male-30.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Geri");

        javax.swing.GroupLayout btn_geriLayout = new javax.swing.GroupLayout(btn_geri);
        btn_geri.setLayout(btn_geriLayout);
        btn_geriLayout.setHorizontalGroup(
            btn_geriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_geriLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_geriLayout.setVerticalGroup(
            btn_geriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_geriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_geriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        btn_yntm_musteri_listele.setBackground(new java.awt.Color(51, 51, 255));
        btn_yntm_musteri_listele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_yntm_musteri_listeleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_yntm_musteri_listeleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_yntm_musteri_listeleMousePressed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-male-30.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Müşteri Listele");

        javax.swing.GroupLayout btn_yntm_musteri_listeleLayout = new javax.swing.GroupLayout(btn_yntm_musteri_listele);
        btn_yntm_musteri_listele.setLayout(btn_yntm_musteri_listeleLayout);
        btn_yntm_musteri_listeleLayout.setHorizontalGroup(
            btn_yntm_musteri_listeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_yntm_musteri_listeleLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        btn_yntm_musteri_listeleLayout.setVerticalGroup(
            btn_yntm_musteri_listeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_yntm_musteri_listeleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_yntm_musteri_listeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout yonetimpanelLayout = new javax.swing.GroupLayout(yonetimpanel);
        yonetimpanel.setLayout(yonetimpanelLayout);
        yonetimpanelLayout.setHorizontalGroup(
            yonetimpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_yntm_uye_listele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_geri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_yntm_uye_ekle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_yntm_uye_guncelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_yntm_uye_sil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_yntm_musteri_listele, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        yonetimpanelLayout.setVerticalGroup(
            yonetimpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yonetimpanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_geri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_yntm_uye_listele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_yntm_uye_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_yntm_uye_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_yntm_uye_sil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_yntm_musteri_listele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", yonetimpanel);

        homepanel.setBackground(new java.awt.Color(51, 51, 255));

        btn_yntm.setBackground(new java.awt.Color(51, 51, 255));
        btn_yntm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_yntmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_yntmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_yntmMousePressed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-male-30.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Yönetim");

        javax.swing.GroupLayout btn_yntmLayout = new javax.swing.GroupLayout(btn_yntm);
        btn_yntm.setLayout(btn_yntmLayout);
        btn_yntmLayout.setHorizontalGroup(
            btn_yntmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_yntmLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_yntmLayout.setVerticalGroup(
            btn_yntmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_yntmLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(btn_yntmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        btn_misafir.setBackground(new java.awt.Color(51, 51, 255));
        btn_misafir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_misafirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_misafirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_misafirMousePressed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-male-30.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Misafir");

        javax.swing.GroupLayout btn_misafirLayout = new javax.swing.GroupLayout(btn_misafir);
        btn_misafir.setLayout(btn_misafirLayout);
        btn_misafirLayout.setHorizontalGroup(
            btn_misafirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_misafirLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        btn_misafirLayout.setVerticalGroup(
            btn_misafirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_misafirLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(btn_misafirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        btn_uye.setBackground(new java.awt.Color(51, 51, 255));
        btn_uye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_uyeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_uyeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_uyeMousePressed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-male-30.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Üye");

        javax.swing.GroupLayout btn_uyeLayout = new javax.swing.GroupLayout(btn_uye);
        btn_uye.setLayout(btn_uyeLayout);
        btn_uyeLayout.setHorizontalGroup(
            btn_uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_uyeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        btn_uyeLayout.setVerticalGroup(
            btn_uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_uyeLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(btn_uyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout homepanelLayout = new javax.swing.GroupLayout(homepanel);
        homepanel.setLayout(homepanelLayout);
        homepanelLayout.setHorizontalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_yntm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_misafir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_uye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homepanelLayout.setVerticalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_yntm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_uye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_misafir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", homepanel);

        sidepanel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 570));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 270, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MousePressed

    private void btn_yntmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntmMousePressed
        /*Yönetim Butonuna tıklanan kodlar için geçerli*/
        jTabbedPane1.setSelectedIndex(0);
        setColor(btn_yntm);
        resetColor(btn_uye);
        resetColor(btn_misafir);
    }//GEN-LAST:event_btn_yntmMousePressed

    private void btn_uyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_uyeMousePressed
        /*Üye Butonuna tıklanan kodlar için geçerli*/
        setColor(btn_uye);
        resetColor(btn_yntm);
        resetColor(btn_misafir);
    }//GEN-LAST:event_btn_uyeMousePressed

    private void btn_misafirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_misafirMousePressed
        /*Misafir Butonuna tıklanan kodlar için geçerli*/
        setColor(btn_misafir);
        resetColor(btn_yntm);
        resetColor(btn_uye);
    }//GEN-LAST:event_btn_misafirMousePressed

    private void btn_yntm_uye_listeleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_listeleMousePressed
        // TODO add your handling code here:
        setColor(btn_yntm_uye_listele);
        resetColor(btn_yntm_uye_ekle);
        resetColor(btn_yntm_uye_guncelle);
        resetColor(btn_yntm_uye_sil);
        resetColor(btn_yntm_musteri_listele);
    }//GEN-LAST:event_btn_yntm_uye_listeleMousePressed

    private void btn_yntm_uye_ekleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_ekleMousePressed
        // TODO add your handling code here:
        setColor(btn_yntm_uye_ekle);
        resetColor(btn_yntm_uye_listele);
        resetColor(btn_yntm_uye_guncelle);
        resetColor(btn_yntm_uye_sil);
        resetColor(btn_yntm_musteri_listele);
    }//GEN-LAST:event_btn_yntm_uye_ekleMousePressed

    private void btn_yntm_uye_guncelleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_guncelleMousePressed
        // TODO add your handling code here:
        setColor(btn_yntm_uye_guncelle);
        resetColor(btn_yntm_uye_ekle);
        resetColor(btn_yntm_uye_listele);
        resetColor(btn_yntm_uye_sil);
        resetColor(btn_yntm_musteri_listele);
    }//GEN-LAST:event_btn_yntm_uye_guncelleMousePressed

    private void btn_yntm_uye_silMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_silMousePressed
        // TODO add your handling code here:
        setColor(btn_yntm_uye_sil);
        resetColor(btn_yntm_uye_ekle);
        resetColor(btn_yntm_uye_guncelle);
        resetColor(btn_yntm_uye_listele);
        resetColor(btn_yntm_musteri_listele);
    }//GEN-LAST:event_btn_yntm_uye_silMousePressed

    private void btn_geriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_geriMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        resetColor(btn_yntm);
    }//GEN-LAST:event_btn_geriMousePressed

    private void btn_yntm_musteri_listeleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_musteri_listeleMousePressed
        // TODO add your handling code here:
        setColor(btn_yntm_musteri_listele);
        resetColor(btn_yntm_uye_listele);
        resetColor(btn_yntm_uye_ekle);
        resetColor(btn_yntm_uye_guncelle);
        resetColor(btn_yntm_uye_sil);
        
    }//GEN-LAST:event_btn_yntm_musteri_listeleMousePressed

    private void btn_geriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_geriMouseEntered
        // TODO add your handling code here:
        setColor(btn_geri);
    }//GEN-LAST:event_btn_geriMouseEntered

    private void btn_geriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_geriMouseExited
        // TODO add your handling code here:
        resetColor(btn_geri);
    }//GEN-LAST:event_btn_geriMouseExited

    private void btn_yntmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntmMouseEntered
        // TODO add your handling code here:
        setColor(btn_yntm);
    }//GEN-LAST:event_btn_yntmMouseEntered

    private void btn_yntmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntmMouseExited
        // TODO add your handling code here:
        resetColor(btn_yntm);
    }//GEN-LAST:event_btn_yntmMouseExited

    private void btn_uyeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_uyeMouseEntered
        // TODO add your handling code here:
        setColor(btn_uye);
    }//GEN-LAST:event_btn_uyeMouseEntered

    private void btn_uyeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_uyeMouseExited
        // TODO add your handling code here:
        resetColor(btn_uye);
    }//GEN-LAST:event_btn_uyeMouseExited

    private void btn_misafirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_misafirMouseEntered
        // TODO add your handling code here:
        setColor(btn_misafir);
    }//GEN-LAST:event_btn_misafirMouseEntered

    private void btn_misafirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_misafirMouseExited
        // TODO add your handling code here:
        resetColor(btn_misafir);
    }//GEN-LAST:event_btn_misafirMouseExited

    private void btn_yntm_uye_listeleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_listeleMouseEntered
        // TODO add your handling code here:
        setColor(btn_yntm_uye_listele);
    }//GEN-LAST:event_btn_yntm_uye_listeleMouseEntered

    private void btn_yntm_uye_listeleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_listeleMouseExited
        // TODO add your handling code here:
        resetColor(btn_yntm_uye_listele);
    }//GEN-LAST:event_btn_yntm_uye_listeleMouseExited

    private void btn_yntm_uye_ekleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_ekleMouseEntered
        // TODO add your handling code here:
        setColor(btn_yntm_uye_ekle);
    }//GEN-LAST:event_btn_yntm_uye_ekleMouseEntered

    private void btn_yntm_uye_ekleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_ekleMouseExited
        // TODO add your handling code here:
        resetColor(btn_yntm_uye_ekle);
    }//GEN-LAST:event_btn_yntm_uye_ekleMouseExited

    private void btn_yntm_uye_guncelleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_guncelleMouseEntered
        // TODO add your handling code here:
        setColor(btn_yntm_uye_guncelle);
    }//GEN-LAST:event_btn_yntm_uye_guncelleMouseEntered

    private void btn_yntm_uye_guncelleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_guncelleMouseExited
        // TODO add your handling code here:
        resetColor(btn_yntm_uye_guncelle);
    }//GEN-LAST:event_btn_yntm_uye_guncelleMouseExited

    private void btn_yntm_uye_silMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_silMouseEntered
        // TODO add your handling code here:
        setColor(btn_yntm_uye_sil);
    }//GEN-LAST:event_btn_yntm_uye_silMouseEntered

    private void btn_yntm_uye_silMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_uye_silMouseExited
        // TODO add your handling code here:
        resetColor(btn_yntm_uye_sil);
    }//GEN-LAST:event_btn_yntm_uye_silMouseExited

    private void btn_yntm_musteri_listeleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_musteri_listeleMouseEntered
        // TODO add your handling code here:
        setColor(btn_yntm_musteri_listele);
    }//GEN-LAST:event_btn_yntm_musteri_listeleMouseEntered

    private void btn_yntm_musteri_listeleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yntm_musteri_listeleMouseExited
        // TODO add your handling code here:
        resetColor(btn_yntm_musteri_listele);
    }//GEN-LAST:event_btn_yntm_musteri_listeleMouseExited

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
        
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xx,y-xy);
                
    }//GEN-LAST:event_bgMouseDragged

    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(0,102,255));
    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(51,51,255));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_geri;
    private javax.swing.JPanel btn_misafir;
    private javax.swing.JPanel btn_uye;
    private javax.swing.JPanel btn_yntm;
    private javax.swing.JPanel btn_yntm_musteri_listele;
    private javax.swing.JPanel btn_yntm_uye_ekle;
    private javax.swing.JPanel btn_yntm_uye_guncelle;
    private javax.swing.JPanel btn_yntm_uye_listele;
    private javax.swing.JPanel btn_yntm_uye_sil;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel logopanel;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel toppanel;
    private javax.swing.JPanel yonetimpanel;
    // End of variables declaration//GEN-END:variables
}
